language: rust
os:
    - linux
env:
    global:
        - secure: YuUsqKnM+ZNtmyXqX3cED2XKlXsFR+C8tRPWhpHamGO9RxxVfiMbWIKg9baDp+VNsQchs+JgYy19+erISC1A1Y0WT/GCSzkp4am2VdOrgRtUqcnWXfgDIKOnDGV+KBTwbcgHG25AnalIpIeSpOIs2IkqhvryY8I1D3rO5JkdZvU=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
