[package]

name    = "pretty"
version = "0.0.1"
authors = [ "Jonathan Sterling <jon@jonmsterling.com>",
            "Darin Morrison <darinmorrison+epsilonz@gmail.com>"
          ]

[lib]
doc     = true
doctest = false
name    = "pretty"
path    = "src/pretty/lib.rs"

[[bin]]
doc  = false
name = "trees"
path = "examples/trees.rs"
