[package]
name = "pretty"
version = "0.3.3"
authors = [ "Jonathan Sterling <jon@jonmsterling.com>", "Darin Morrison <darinmorrison+git@gmail.com>" ]
description = "Wadler-style pretty-printing combinators in Rust"
documentation = "https://docs.rs/pretty/"
keywords = ["console", "functional", "pretty-printing"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/freebroccolo/pretty.rs"

[dependencies]
typed-arena = "1.2.0"
termcolor = "0.3"

[dev-dependencies]
tempfile = "2.1.4"
