[package]

name = "pretty"
version = "0.0.1"
authors = ["Jonathan Sterling <jon@jonmsterling.com>"]

[lib]
name = "pretty"
path = "src/pretty/lib.rs"

[[bin]]
name = "trees"
path = "examples/trees.rs"
